apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  title: test-backstage
  description: ""
  annotations:
    github.com/project-slug: default/test-backstage
    backstage.io/view-url: ""
    backstage.io/techdocs-ref: dir:.
  tags:
    - rails
    - rails#7-0
    - ruby
    - ruby#3-1
spec:
  type: service
  owner: unknown
  lifecycle: production
